language: python

python:
  - "2.7"
  - "3.5"

sudo: false

install:
  - "pip install six"
  - "make install"

script:
  - make quality
  - make test

branches:
    only:
      - master

after_success: coveralls
